name:  warp-scanner

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/50 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
        pip install cryptography 
        pip install requests
        
    - name: Run script
      run: python warpauto.py
       
    - name: Commit and push changes
      run: |          
          git config --global user.email "darknessm.427@gmail.com"
          git config --global user.name "darknessm427"
          git config credential.helper store
          git add -A
          git commit -m "👾 Auto update - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M')"
          git push
